# Generated by Django 3.2.18 on 2024-06-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostAndFound', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditems',
            name='itemtype',
        ),
        migrations.RemoveField(
            model_name='lostitems',
            name='itemtype',
        ),
        migrations.AddField(
            model_name='founditems',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='founditems',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='founditems',
            name='itemType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='founditems',
            name='keywords',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='founditems',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='itemType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='keywords',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='itemName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='itemName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
