# Generated by Django 3.2.18 on 2024-06-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostAndFound', '0002_auto_20240616_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditems',
            name='contact',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='itemName',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='itemType',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='keywords',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='contact',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='itemName',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='itemType',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='keywords',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
