# Generated by Django 3.2.18 on 2024-06-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostAndFound', '0003_auto_20240617_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditems',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lostitems',
            name='image',
        ),
        migrations.AlterField(
            model_name='founditems',
            name='date',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='founditems',
            name='time',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='date',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='time',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
