# Generated by Django 3.2.18 on 2024-06-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostAndFound', '0009_alter_founditems_image_alter_lostitems_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditems',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lostitems',
            name='id',
        ),
        migrations.AddField(
            model_name='founditems',
            name='submissionID',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='submissionID',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False),
        ),
    ]
