# Generated by Django 3.2.18 on 2024-06-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostAndFound', '0010_auto_20240619_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditems',
            name='id',
            field=models.BigAutoField(auto_created=True, default='0', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostitems',
            name='id',
            field=models.BigAutoField(auto_created=True, default='0', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='founditems',
            name='submissionID',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='submissionID',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
