# Generated by Django 3.2.18 on 2024-06-19 07:01

from django.db import migrations
import lostAndFound.models


class Migration(migrations.Migration):

    dependencies = [
        ('lostAndFound', '0011_auto_20240619_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditems',
            name='submissionID',
            field=lostAndFound.models.FoundIDField(max_length=36),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='submissionID',
            field=lostAndFound.models.LostIDField(max_length=36),
        ),
    ]
